### ISSUE TITLE
关于模块扫描信道的问题？

### ISSUE THREAD

**Issue by yanqiaoyu** [jolin90/smartconfig#2]
您好，请问您是如何解决模块扫描不同channel 的问题的？

**Comment by jolin90** [comment]
timer_t timerid = 0;
	struct sigevent evp;

	evp.sigev_notify = SIGEV_THREAD;
	evp.sigev_notify_function = timer_thread;
	if (timer_create(CLOCK_REALTIME, &evp, &timerid) == -1) {
		error("fail to timer_create");
		goto error_iface;
	}
	struct itimerspec it;
	it.it_interval.tv_sec = 0;
	it.it_interval.tv_nsec = 1000 * 1000 * 300;
	it.it_value.tv_sec = 0;
	it.it_value.tv_nsec = 1000 * 1000 * 300;
	if (timer_settime(timerid, 0, &it, NULL) == -1) {
		perror("fail to timer_settime");
		goto error_socket;
	}

Setting timer clock. regularly call the function timer_thread, and change channel.
